project_id = "jyaiiywzzxebupfvcnbq"
SUPABASE_URL = "https://jyaiiywzzxebupfvcnbq.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5YWlpeXd6enhlYnVwZnZjbmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMjY2NjEsImV4cCI6MjA5NjYwMjY2MX0.Wl4gEFBTYBnq51zvNtdAzNlyOG1J_ofb2KOfEgoYEZI"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5YWlpeXd6enhlYnVwZnZjbmJxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTAyNjY2MSwiZXhwIjoyMDk2NjAyNjYxfQ.xpECEN3d9G5hYDQYSkmwPgjRJxwRKcRlKv5dWzGcAb4"
