/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedNovosNegociosRouteImport } from './routes/_authenticated/novos-negocios'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMaRouteImport } from './routes/_authenticated/ma'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComitesIndexRouteImport } from './routes/_authenticated/comites/index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated/projetos/$id'
import { Route as AuthenticatedComitesIdRouteImport } from './routes/_authenticated/comites/$id'
import { Route as ApiPublicHooksNotifyTarefasRouteImport } from './routes/api/public/hooks/notify-tarefas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovosNegociosRoute =
  AuthenticatedNovosNegociosRouteImport.update({
    id: '/novos-negocios',
    path: '/novos-negocios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaRoute = AuthenticatedMaRouteImport.update({
  id: '/ma',
  path: '/ma',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComitesIndexRoute =
  AuthenticatedComitesIndexRouteImport.update({
    id: '/comites/',
    path: '/comites/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComitesIdRoute = AuthenticatedComitesIdRouteImport.update({
  id: '/comites/$id',
  path: '/comites/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksNotifyTarefasRoute =
  ApiPublicHooksNotifyTarefasRouteImport.update({
    id: '/api/public/hooks/notify-tarefas',
    path: '/api/public/hooks/notify-tarefas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/ma': typeof AuthenticatedMaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/novos-negocios': typeof AuthenticatedNovosNegociosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/comites/$id': typeof AuthenticatedComitesIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/comites/': typeof AuthenticatedComitesIndexRoute
  '/api/public/hooks/notify-tarefas': typeof ApiPublicHooksNotifyTarefasRoute
}
export interface FileRoutesByTo {
  '/aceitar-convite': typeof AceitarConviteRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/ma': typeof AuthenticatedMaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/novos-negocios': typeof AuthenticatedNovosNegociosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/': typeof AuthenticatedIndexRoute
  '/comites/$id': typeof AuthenticatedComitesIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/comites': typeof AuthenticatedComitesIndexRoute
  '/api/public/hooks/notify-tarefas': typeof ApiPublicHooksNotifyTarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/ma': typeof AuthenticatedMaRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/novos-negocios': typeof AuthenticatedNovosNegociosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/comites/$id': typeof AuthenticatedComitesIdRoute
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/comites/': typeof AuthenticatedComitesIndexRoute
  '/api/public/hooks/notify-tarefas': typeof ApiPublicHooksNotifyTarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/login'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/ma'
    | '/notificacoes'
    | '/novos-negocios'
    | '/tarefas'
    | '/comites/$id'
    | '/projetos/$id'
    | '/api/public/bootstrap-admin'
    | '/comites/'
    | '/api/public/hooks/notify-tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aceitar-convite'
    | '/login'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/ma'
    | '/notificacoes'
    | '/novos-negocios'
    | '/tarefas'
    | '/'
    | '/comites/$id'
    | '/projetos/$id'
    | '/api/public/bootstrap-admin'
    | '/comites'
    | '/api/public/hooks/notify-tarefas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/_authenticated/ma'
    | '/_authenticated/notificacoes'
    | '/_authenticated/novos-negocios'
    | '/_authenticated/tarefas'
    | '/_authenticated/'
    | '/_authenticated/comites/$id'
    | '/_authenticated/projetos/$id'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/comites/'
    | '/api/public/hooks/notify-tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  LoginRoute: typeof LoginRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicHooksNotifyTarefasRoute: typeof ApiPublicHooksNotifyTarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/novos-negocios': {
      id: '/_authenticated/novos-negocios'
      path: '/novos-negocios'
      fullPath: '/novos-negocios'
      preLoaderRoute: typeof AuthenticatedNovosNegociosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ma': {
      id: '/_authenticated/ma'
      path: '/ma'
      fullPath: '/ma'
      preLoaderRoute: typeof AuthenticatedMaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comites/': {
      id: '/_authenticated/comites/'
      path: '/comites'
      fullPath: '/comites/'
      preLoaderRoute: typeof AuthenticatedComitesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comites/$id': {
      id: '/_authenticated/comites/$id'
      path: '/comites/$id'
      fullPath: '/comites/$id'
      preLoaderRoute: typeof AuthenticatedComitesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/notify-tarefas': {
      id: '/api/public/hooks/notify-tarefas'
      path: '/api/public/hooks/notify-tarefas'
      fullPath: '/api/public/hooks/notify-tarefas'
      preLoaderRoute: typeof ApiPublicHooksNotifyTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedMaRoute: typeof AuthenticatedMaRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovosNegociosRoute: typeof AuthenticatedNovosNegociosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComitesIdRoute: typeof AuthenticatedComitesIdRoute
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRoute
  AuthenticatedComitesIndexRoute: typeof AuthenticatedComitesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedMaRoute: AuthenticatedMaRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovosNegociosRoute: AuthenticatedNovosNegociosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComitesIdRoute: AuthenticatedComitesIdRoute,
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRoute,
  AuthenticatedComitesIndexRoute: AuthenticatedComitesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  LoginRoute: LoginRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicHooksNotifyTarefasRoute: ApiPublicHooksNotifyTarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
